/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TodoCreateImport } from './routes/todo/create'
import { Route as TodoIdImport } from './routes/todo/$id'
import { Route as AuthenticationRegisterImport } from './routes/authentication/register'
import { Route as AuthenticationLoginImport } from './routes/authentication/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodoCreateRoute = TodoCreateImport.update({
  id: '/todo/create',
  path: '/todo/create',
  getParentRoute: () => rootRoute,
} as any)

const TodoIdRoute = TodoIdImport.update({
  id: '/todo/$id',
  path: '/todo/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationRegisterRoute = AuthenticationRegisterImport.update({
  id: '/authentication/register',
  path: '/authentication/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationLoginRoute = AuthenticationLoginImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginImport
      parentRoute: typeof rootRoute
    }
    '/authentication/register': {
      id: '/authentication/register'
      path: '/authentication/register'
      fullPath: '/authentication/register'
      preLoaderRoute: typeof AuthenticationRegisterImport
      parentRoute: typeof rootRoute
    }
    '/todo/$id': {
      id: '/todo/$id'
      path: '/todo/$id'
      fullPath: '/todo/$id'
      preLoaderRoute: typeof TodoIdImport
      parentRoute: typeof rootRoute
    }
    '/todo/create': {
      id: '/todo/create'
      path: '/todo/create'
      fullPath: '/todo/create'
      preLoaderRoute: typeof TodoCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/register': typeof AuthenticationRegisterRoute
  '/todo/$id': typeof TodoIdRoute
  '/todo/create': typeof TodoCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/register': typeof AuthenticationRegisterRoute
  '/todo/$id': typeof TodoIdRoute
  '/todo/create': typeof TodoCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/register': typeof AuthenticationRegisterRoute
  '/todo/$id': typeof TodoIdRoute
  '/todo/create': typeof TodoCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication/login'
    | '/authentication/register'
    | '/todo/$id'
    | '/todo/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication/login'
    | '/authentication/register'
    | '/todo/$id'
    | '/todo/create'
  id:
    | '__root__'
    | '/'
    | '/authentication/login'
    | '/authentication/register'
    | '/todo/$id'
    | '/todo/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationRegisterRoute: typeof AuthenticationRegisterRoute
  TodoIdRoute: typeof TodoIdRoute
  TodoCreateRoute: typeof TodoCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationRegisterRoute: AuthenticationRegisterRoute,
  TodoIdRoute: TodoIdRoute,
  TodoCreateRoute: TodoCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authentication/login",
        "/authentication/register",
        "/todo/$id",
        "/todo/create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authentication/login": {
      "filePath": "authentication/login.tsx"
    },
    "/authentication/register": {
      "filePath": "authentication/register.tsx"
    },
    "/todo/$id": {
      "filePath": "todo/$id.tsx"
    },
    "/todo/create": {
      "filePath": "todo/create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
